version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/biblioteca
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
    depends_on:
      - db
    networks:
      - biblioteca-network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=biblioteca
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - biblioteca-network

volumes:
  mysql-data:

networks:
  biblioteca-network:
    driver: bridge
